#--------------------------------------------
#Student’s Name:             June Bonogofski
#Lab #5               		lab4E1.c
#Lab Section:                X01-L
#Lab Instructor’s Name:      Dhara Wagh
#Lecture Instructor’s Name:  Ardy RD
#--------------------------------------------

CC =gcc
CFLAGS =-Wall -std=c99

lab5E1: dynamicArray.o lab5E1.c
	$(CC) $(CFLAGS) $? -o $@

clean: dynamicArray.o lab5E1
	rm $?